references:
  github-defaults: &github-defaults
    org: RedisLabsModules
    extension: zip

libs:
  redis:
    github:
      <<: *github-defaults
      org: antirez
      name: redis
      release: 5.0.2
  rejson:
    github:
      <<: *github-defaults
      name: rejson
      release: 08b10ce3045f9b24cf69ae00d25bee18f8807154
  redisbloom:
    github:
      <<: *github-defaults
      name: rebloom
      release: 955989f38778916f1bde0dc6998626333233d283
  redisml:
    github:
      <<: *github-defaults
      name: redis-ml
      release: 9bc5814ab3fcc8ea33edd0c060c0f84eead05c28
  redisgraph:
    github:
      <<: *github-defaults
      name: RedisGraph
      release: v1.0.4
  redisearch:
    github:
      <<: *github-defaults
      name: RediSearch
      release: v1.4.2
  redex:
    github:
      <<: *github-defaults
      name: redex
      release: f2d35edf438f1ac2279c312056589ddf83af6efc



