version: 2.1

orbs:
  docker-publish: circleci/docker-publish@1.0.0

executors:
    linux-executor:
      docker:
        - image: digitaltownorg/circleci:app
          user: root

      environment:
        CC_TEST_REPORTER_ID: 1ce2c894983929f01f1a2e38b99f695de00efa01a38043280c6849761de2578a

      working_directory: ~/project

jobs:
  setup:
    executor: circleci/docker-publish

    steps:
      - checkout

      - docker-publish/check

      # - run:
      #     name: Install goss
      #     command: |
      #       # rather than give internet scripts SU rights, we install to local user bin and add to path
      #       mkdir ~/bin
      #       export GOSS_DST=~/bin
      #       export PATH=$PATH:~/bin
      #       curl -fsSL https://goss.rocks/install | sh
      #       goss -version

      # - docker-publish/publish:
      #     after_checkout:
      #       - run:
      #           name: Do this after checkout.
      #           command: echo "Did this after checkout"
      #     before_build:
      #       - run:
      #           name: Do this before the build.
      #           command: echo "Did this before the build"
      #     after_build:
      #       - run:
      #           name: Do this after the build.
      #           command: echo "Did this after the build"

workflows:
  version: 2.1

  test:
    jobs:
      - setup
